# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
#     {id: 0, size: 0.0475, name: marker_0},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'table_black',
      layout:
        [
          {id: 0, size: 0.0445, x: 0.37465, y: -0.216, z: 0.15, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'wall_red',
      layout:
        [
          {id: 1, size: 0.0445, x: -1.0, y: 0.0, z: 0.025, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    # {
    #   name: 'wall_white',
    #   layout:
    #     [
    #       {id: 2, size: 0.0715, x: 0.10, y: 0.0, z: 0.025, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #       {id: 3, size: 0.0715, x: 0.235, y: 0.0, z: 0.025, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #     ]
    # },
    {
      name: 'table_wooden',
      layout:
        [
          {id: 3, size: 0.0445, x: 0.56, y: -0.344, z: 0.15, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },

  ]


#,        
# {id: 3, size: 0.0445, x: 0.01, y: 0.0, z: 0.025, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}